### PR TITLE
Validation of Sec-WebSocket-Protocol on the connector side

### PR DESCRIPTION
**Pull request by jitsni**
Validation of Sec-WebSocket-Protocol on the connector side
Since the header is comma separated value list, it is stored as multiple values

This fixes https://github.com/kaazing/gateway/issues/315

### CODE REVIEW

**Comment by jitsni** [comment]
It needs k3po PR https://github.com/k3po/k3po/pull/322

**Comment by dpwspoon** [comment]
I believe K3po has been released: 3.0.0-alpha-27

**Comment by jitsni** [comment]
Yes, I integrated the latest k3po in this branch, gateway builds fines. But enterprise.gateway has some NPEs which I need to investigate.

**Comment by jitsni** [comment]
Now it is ready for review and merge

**Comment by dpwspoon** [comment]
I think we should revert this for now as we don't have an API to set the expected next protocol on the connector yet... And some proxies (ours included) art strict to the spec.  Once we have that API I think we should add this back in

**Comment by dpwspoon** [comment]
Reasoning for reverting this is here: https://github.com/kaazing/gateway/issues/472#issuecomment-201508244

**Pull request merged**
