### PR TITLE
Added SPI note for issue #116

### PR DESCRIPTION
**Pull request by vjwang**
Added the migration path for SPIs from 4.x to 5.x

### CODE REVIEW

**Comment by vjwang** [comment]
@michaelcretzman Please review the new text. See related issue #116.

**Comment by michaelcretzman** [comment]
@vjwang , this is verified.

**Comment by vjwang** [comment]
Thanks, @michaelcretzman

**Comment by vjwang** [comment]
@dpwspoon Please merge this verified fix.

**Pull request merged**
