### PR TITLE
Fix the diagnostic message for unexpected exception to include session details

### PR DESCRIPTION
**Pull request by stanculescu**
Added unit test in transport/wsn module.

### CODE REVIEW

**Comment by stanculescu** [comment]
Hello @cmebarrow , this is my first attempt to fix issue #685. Can you please review ? I don't have the rights yet to add you as assignee of the PR.

**Comment by sbadugu** [comment]
@stanculescu I added you to the list, you should now have permissions to add assignees.

**Comment by cmebarrow** [comment]
Travis build failed in mina.netty:
```
Failed tests: 
  DefaultNioSocketChannelIoSessionConfigTest.testSetAllSendBufferSize:122 expected:<2048> but was:<2304>
  DefaultNioSocketChannelIoSessionConfigTest.testSetAllTrafficClass:161 expected:<2> but was:<0>
```
Restarted.

**Comment by Anisotrop** [comment]
The two tests seem to fail on Ubuntu even on develop branch. They were skipped by default this is why Travis builds passed until now. I have created a [PR](https://github.com/stanculescu/gateway/pull/2) that ignores those tests and links to a newly created issue.

**Comment by cmebarrow** [comment]
@stanculescu Please merge @Anisotrop 's PR (it will go into this PR) so I merge this one.

**Pull request merged**
