### PR TITLE
Forward port to 5.x: Identity logging for HTTP transport, TCP fallback #91

### PR DESCRIPTION
**Pull request by msalavastru**

### CODE REVIEW

**Comment by msalavastru** [comment]
The tests in WsxAcceptorLoggingIT have been fixed in the last PR of forward porting to 5.x : [PR 381](https://github.com/kaazing/gateway/pull/381)

**Comment by cmebarrow** [comment]
@msalavastru Mihai please pull in the latest changes from develop branch so I can merge this PR. Let me know if you are still seeing any test failures and I can help you with them tomorrow. I am thinking I might just merged his PR directly instead of merging the preceding ones since I think it includes them all. WDYT?

**Comment by msalavastru** [comment]
@cmebarrow I have pulled all the latest changes in all the PR's that I created for the forward port. There were some merging conflicts because there were changes in some of the files that these PR's also changed, but I fixed them.

I think it is good to include the PR that has all the changes from the previous ones. 

If you want to do that, then this is the [PR 380](https://github.com/kaazing/gateway/pull/380) that contains all the changes from the previous ones, including this current PR, and two more plus some minor fixes for the tests. In [PR 380](https://github.com/kaazing/gateway/pull/380) all the tests pass. This is the one you should merge. See the comment [here](https://github.com/kaazing/gateway/pull/380#issuecomment-168986049) for a recap of what PR's it includes for the forward port.

**Comment by cmebarrow** [comment]
Merged as part of PR https://github.com/kaazing/gateway/pull/380

**Pull request closed without merging**
