### PR TITLE
Refactor ResourceAddresses in order to support generic Strings instead of URIs

### PR DESCRIPTION
**Pull request by irina-mitrea-luxoft**
Added first batch of changes for refactoring URIs to Strings

### CODE REVIEW

**Comment by irina-mitrea-luxoft** [comment]
@jitsni Hello, Jitu, I have added a first batch of changes for the refactoring. The implementation is at an initial stage and is not finalized. Can you please provide feedback regarding this?

**Comment by irina-mitrea-luxoft** [comment]
@jitsni Hello, Jitu. Also, regarding refactoring existing URI-specific functionality, e.g.:
- uri.getAuthority()
- uri.getScheme()
- uri.getPath()
- uri.getHost()

I was thinking of defining a wrapper class over String which parses the initial String into relevant tokens, similarly to how URI objects do parsing. 

Relevant code example (ResourceAddressFactory.java, row 146):
>
ResourceAddressFactorySpi<?> resourceAddressFactory = findResourceAddressFactory(location.getScheme());//location is an URI object here

would be refactored to something similar to
>
StringURIWrapper stringURIWrapper = new StringURIWrapper(location);//location is a String object here, StringURIWrapper is a customly defined object
ResourceAddressFactorySpi<?> resourceAddressFactory = findResourceAddressFactory(stringURIWrapper.getScheme());

Another alternative may be represented by refactoring ResourceAdress URI parameters to  StringURIWrappers instead of Strings.

Can you please comment on the above and provide your input? Thank you.

**Comment by jitsni** [comment]
I would just use few util functions to get scheme etc. for now. The util function
-  perhaps would delegate to URI. If it fails, use rudimentary parsing.
- Or preprocess the string a bit and pass it URI

**Comment by irina-mitrea-luxoft** [comment]
@jitsni @sbadugu  Hello, Jitu, I have performed a reset soft to the previous push of the branch (removing all my extra commits) and it seems that github considers that in this scenario a merge was performed and the pull request was automatically closed - although no merge was actually performed. I will create a new pull request with changes

**Pull request closed without merging**
