### PR TITLE
fix for gateway ticket 434

### PR DESCRIPTION
**Pull request by danibusu**
- validate if masking expected/required when decoding a WS frame
- update HTTP request parsing state machine to validate partial HTTP
  method

### CODE REVIEW

**Comment by danibusu** [comment]
This pull request should be merged after [this](https://github.com/k3po/k3po/pull/352) one is merged and k3po released.

**Comment by danibusu** [comment]
Because I changed the code to reject unmasked frames when gateway is acting as a server in a WS connection, more ITs will fail, as they are no written according to spec. I'll change the ITs only after the current changes are approved by a reviewer, as I'm certain it will mean a lot of extra work.

**Comment by danibusu** [comment]
@dpwspoon This pull request is related to the one I opened on the k3po repository regarding client frame masking. If you could take a look, it would be great. Thanks!

**Comment by dpwspoon** [comment]
Thanks @danibusu.  Looks ok to me, but I'd like to get @jitsni to weigh in on the addition of the validate method to netty, as he is more familiar with those decoders and might know of a way to do that with out the API change.

Also, please ensure that [these test](https://github.com/kaazing/gateway/blob/71d1188b365bcfadf12320c4e6d7b354d9f887d6/transport/wsn/src/test/java/org/kaazing/gateway/transport/wsn/specification/ws/acceptor/MaskingIT.java) can now be un ignored.

@jfallows you asked to be referenced in this PR to see why we needed the masking fix.  I believe the answer to you question was that we weren't running the K3po tests (they were ignored)...

**Comment by danibusu** [comment]
@jitsni @dpwspoon Updated some ITs that were failing because of the masking change. Could you please perform a k3po release, so I can update the dependency version in the gateway pom? This PR should not be merged until then. Thanks!

**Comment by dpwspoon** [comment]
I've scheduled a release: http://jenkins.kaazing.wan/view/release_build/job/k3po-release/

**Comment by danibusu** [comment]
Merged changes from develop branch to get the update to the latest k3po version.

**Comment by dpwspoon** [comment]
Removing me as assignee as looks good to me.  @jitsni this is in your court

**Comment by jitsni** [comment]
I think masking and the partial buffer validation should be separated into separate PRs.

**Comment by sbadugu** [comment]
@danibusu Can you please take an action item on this PR ?

**Comment by danibusu** [comment]
@sbadugu @jitsni As requested, I've raised two new PRs, [PR 775](https://github.com/kaazing/gateway/pull/775) for the WS client masking issue and [PR 778](https://github.com/kaazing/gateway/pull/778) for the partial buffer validation and assigned Jitu to both.

**Comment by sbadugu** [comment]
PRs: 
- [x] kaazing/gateway#775
- [ ] kaazing/gateway#778

**Pull request closed without merging**
