### PR TITLE
Forward Port to 5.x: Transport logging fixes (ipv6, wseb, remove /) #87

### PR DESCRIPTION
**Pull request by msalavastru**
Forward port from gateway.server 4.x of [Transport logging fixes (ipv6, wseb, remove /) ](https://github.com/kaazing-private/gateway.server/pull/87)

### CODE REVIEW

**Comment by cmebarrow** [comment]
@msalavastru Please catch up to latest develop (git pull upstream develop) so I can merge if this (then it will not contain the changes from your PR #370 which I just merged)

**Comment by msalavastru** [comment]
@cmebarrow I have fetched/merged all the latest changes from upstream/develop.

**Comment by cmebarrow** [comment]
@msalavastru This looks fine except the build failed on Travis (failure to compile LoggingFilterTest). Did you not see this failure on your machine? Solution is to add a test dependency on ws.resource.address to transport/spi/pom.xml:
```
diff --git a/transport/spi/pom.xml b/transport/spi/pom.xml
index 435d938..34362f5 100644
--- a/transport/spi/pom.xml
+++ b/transport/spi/pom.xml
@@ -60,6 +60,12 @@
             <scope>test</scope>
         </dependency>
         <dependency>
+            <groupId>org.kaazing</groupId>
+            <artifactId>gateway.resource.address.ws</artifactId>
+            <version>${project.version}</version>
+            <scope>test</scope>
+        </dependency>
+        <dependency>
             <groupId>org.jmock</groupId>
             <artifactId>jmock-junit4</artifactId>
             <scope>test</scope>
```

**Comment by msalavastru** [comment]
@cmebarrow I have added the 2 test dependencies. The Travis build fails on getUserIdentifierShouldReturnTcpEndpointFromTransport(org.kaazing.gateway.transport.LoggingFilterTest), but once the changes from [PR 91 Identity logging for HTTP transport, TCP fallback](https://github.com/kaazing-private/gateway.server/pull/91) will be ported, the test will pass.

**Comment by msalavastru** [comment]
@cmebarrow I am still having problems with some tests failing, even after forward porting Identity Logging #91, I have to investigate further and see what can be done. Hopefully I will be able to finish on Monday.

**Comment by cmebarrow** [comment]
@msalavastru Mihai please pull in the latest changes from develop branch and see if the tests now pass. Let me know if not and if you're stuck and I have a look tomorrow.

**Comment by cmebarrow** [comment]
Merged as part of PR https://github.com/kaazing/gateway/pull/380

**Pull request closed without merging**
