### PR TITLE
updated travis.yml to make sonar analyses on master and release

### PR DESCRIPTION
**Pull request by AdrianCozma**

### CODE REVIEW

**Comment by AdrianCozma** [comment]
@dpwspoon I updated the travis builds to publish on master and release branches as well. and added `-Dsonar.branch=...` so that each branch will have a separate project in sonarqube

I also added `-fn` to the maven command so that this way all the modules run their tests even if one fails, this way we cand identify multiple test fails per run as the expense of a less readable log, please let me know if you think this is ok

**Comment by AdrianCozma** [comment]
does the cobertura command run the tests again?(this is how it looks from the logs); if yes, is this intended? I thought the cobertura command should only provide coverage information(not run the tests again)

**Comment by AdrianCozma** [comment]
the travis build failed with:
```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0:report (default-cli) on project gateway: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]
```

**Comment by dpwspoon** [comment]
This appears to be failing on uploads to sonarqube? And thus shouldn't be merged yet...?

**Comment by AdrianCozma** [comment]
It's not doing the upload to sonarqube since this is a pull request, it's failing when trying to upload to coveralls `Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity` not sure who configured this or the cobertura plugin

**Comment by AdrianCozma** [comment]
Please also see the above [comment](https://github.com/kaazing/gateway/pull/532#issuecomment-210503472) about the tests being run twice

**Comment by dpwspoon** [comment]
Ok, lets remove the coveralls upload reports please (since we chose to use sonarqube).  It is somewhat intentional that they run twice (once with POJO compilation) and once when the corbetura code is injected.   If we trust the corbetura code not to have side effects then I'm ok changing it to run once.

**Comment by AdrianCozma** [comment]
I'm not sure about what effect cobertura has on the build, please let me know if we should keep it

**Comment by dpwspoon** [comment]
No lets just remove it please

**Comment by AdrianCozma** [comment]
travis build passed

**Pull request merged**
