### PR TITLE
Forward port to 5.x: (tickets#180) Avoid ClassCastException in LoggingFilter using socks transport #88

### PR DESCRIPTION
**Pull request by msalavastru**

### CODE REVIEW

**Comment by cmebarrow** [comment]
@msalavastru Please catch up to latest develop (git pull upstream develop) so I can merge if this (then it will not contain the changes from your PR #370 which I just merged)

**Comment by msalavastru** [comment]
@cmebarrow I have fetched/merged all the latest changes from upstream/develop.

**Comment by cmebarrow** [comment]
Changes look good, but I'll have to hold off merging this one until https://github.com/kaazing/gateway/pull/376 is merged.

**Comment by cmebarrow** [comment]
@msalavastru Mihai please pull in the latest changes from develop branch again (there are conflicts now)

**Comment by cmebarrow** [comment]
Merged as part of PR https://github.com/kaazing/gateway/pull/380

**Pull request closed without merging**
