### PR TITLE
Closing wse pending writer when the wse session is closed

### PR DESCRIPTION
**Pull request by jitsni**

### CODE REVIEW

**Comment by dpwspoon** [comment]
@jitsni  Can you do a catch up merge.  And should this go into the RC?

**Comment by jitsni** [comment]
Not needed for RC

**Comment by jitsni** [comment]
@cmebarrow do you think we need this one ? If it is required then I will do catchup merge on this branch.

**Comment by cmebarrow** [comment]
@jitsni Looks like a reasonable change. What motivated making the change? Is there a test case that was failing?

**Comment by jitsni** [comment]
@cmebarrow It just feels like the pending writer is not closed. I don't have a test case. Also, I haven't observed any failure in existing test cases.

**Comment by sbadugu** [comment]
@dpwspoon @jitsni Can we merge this PR ?

**Comment by dpwspoon** [comment]
@jitsni Please do a catch up merge and or close.  We can get this in next rc and run full regression tests to make sure there is no race

**Comment by jitsni** [comment]
Closing this for now.

**Pull request closed without merging**
