### PR TITLE
Added HTTPX tests for gateway.

### PR DESCRIPTION
**Pull request by a-zuckut**

### CODE REVIEW

**Comment by cmebarrow** [comment]
@pkhanal Prashant, I think this looks ok but reassigning to you for final verification and merge since you've been working with Alex a lot on similar stuff (and even probably this)

**Comment by cmebarrow** [comment]
@pkhanal k3po with the httpx spec project will have to be released before you can merge this

**Comment by pkhanal** [comment]
This can be merged once K3PO is released.

**Comment by sanjay-saxena** [comment]
This is not needed anymore as my PR will include the necessary changes.

**Pull request closed without merging**
