### PR TITLE
Changes for time unit conversion.

### PR DESCRIPTION
**Pull request by vmaraloiu**

### CODE REVIEW

**Comment by vmaraloiu** [comment]
This should not be merged yet. I am currently working on a integration test that should validate the fix.

**Comment by jitsni** [comment]
I suppose a unit test can validate the fix. See the following in AcceptOptionsTest.java. That should pass with this fix.

```
    @Test
    public void testWsInactivityTimeout() throws Exception {
        expectSuccess("ws.inactivity.timeout", "60", "ws.inactivityTimeout", 60000L, "http[http/1.1].keepAliveTimeout", 60);
        expectSuccess("ws.inactivity.timeout", "60s", "ws.inactivityTimeout", 60000L, "http[http/1.1].keepAliveTimeout", 60);
        //https://github.com/kaazing/gateway/issues/595
        //expectSuccess("ws.inactivity.timeout", "60000ms", "ws.inactivityTimeout", 60000L, "http[http/1.1].keepAliveTimeout", 60);
    }
```

**Comment by vmaraloiu** [comment]
@jitsni I have performed some changes on the PR, in order to fix the failing tests which occurred on travis after my previous commit. I have also tested with the test scenario as you suggested by uncommenting the line:
```expectSuccess("ws.inactivity.timeout", "60000ms", "ws.inactivityTimeout", 60000L, "http[http/1.1].keepAliveTimeout", 60);```
and the test passed successfully. Can you please provide your feedback on this.

**Comment by jitsni** [comment]
I think you want to add some more unit tests to ParseTimeIntervalTest.java. 
Take a value say 6000000 ms and convert into ms, sec, hours, days, weeks, years (all units).
Take a value say 2 days and convert into ms, sec, hours, days, weeks, years (all units)

Basically, I want to have some tests that cover all the unit conversions (unit x unit i.e two dimensions)

**Pull request merged**
