### PR TITLE
Removed behavior to always send "Cache-control: max-age=0" header 

### PR DESCRIPTION
**Pull request by mgherghe**
Forward port of [PR](https://github.com/kaazing-private/gateway.server/pull/135) in 4.x, which has not been merged yet.

### CODE REVIEW

**Comment by sanjay-saxena** [comment]
@mgherghe  -- `ConfigEnforcementTest` is failing on Travis:

```
Running org.kaazing.gateway.server.config.parse.ConfigEnforcementTest
0    [main] ERROR Gateway  - Validation errors in gateway configuration file
25   [main] ERROR Gateway  -   Invalid XML: error: The document is not a gateway-config@http://xmlns.kaazing.org/2016/03/gateway: document element namespace mismatch expected "http://xmlns.kaazing.org/2016/03/gateway" got "http://xmlns.kaazing.com/2012/03/gateway"
30   [main] ERROR Gateway  - Validation errors in gateway configuration file
30   [main] ERROR Gateway  -   Invalid XML: error: The document is not a gateway-config@http://xmlns.kaazing.org/2016/03/gateway: document element namespace mismatch expected "http://xmlns.kaazing.org/2016/03/gateway" got "http://xmlns.kaazing.com/2012/03/gateway"
35   [main] ERROR Gateway  - Validation errors in gateway configuration file
35   [main] ERROR Gateway  -   Invalid XML: error: The document is not a gateway-config@http://xmlns.kaazing.org/2016/03/gateway: document element namespace mismatch expected "http://xmlns.kaazing.org/2016/03/gateway" got "http://xmlns.kaazing.com/2012/03/gateway"
Tests run: 11, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 1.045 sec <<< FAILURE! - in org.kaazing.gateway.server.config.parse.ConfigEnforcementTest
```

Is it related to these changes?

**Comment by dpwspoon** [comment]
The use case for the translators is that old configs can be translated to latest versions.  This is missing the newest namespace in 4.x gateway (http://xmlns.kaazing.com/2015/11/gateway) meaning that will fail to translate.  I believe this 2016 namespace should probably be http://xmlns.kaazing.com/2015/11/gateway as they were both changed for the same reason?  Note: we will also need to add this to enterprise.gateway.

**Comment by mgherghe** [comment]
I renamed the namespace and fixed the ConfigEnforcementTest failures. I will finish with the changes in enterprise and create a PR on Monday.

**Comment by sanjay-saxena** [comment]
Even though the build got stalled on Travis after multiple restarts, I have merged this pull-request as I don't the issues on Travis are related to it.

**Pull request merged**
