### PR TITLE
Remove code for KSESSIONID and "recycle" authorization mode

### PR DESCRIPTION
**Pull request by sanjay-saxena**
Since we no longer support 3.5 clients, removed code for `KSESSIONID` and `recycle` authorization mode.

### CODE REVIEW

**Comment by sanjay-saxena** [comment]
@cmebarrow, @chao-sun-kaazing -- Please review as we do not have anybody who owns this code.

**Comment by cmebarrow** [comment]
@sanjay-saxena LGTM. Did you run enterprise.gateway.itests to check it doesn't break anything? @chao-sun-kaazing Are there any client itests this change might break?

**Comment by sanjay-saxena** [comment]
@cmebarrow -- Yes, I already ran enterprise.gateway.itests and did not see any regressions.

**Comment by chao-sun-kaazing** [comment]
@cmebarrow itests do not use recycle mode. it is good to be merged

**Pull request merged**
