### PR TITLE
Pull request holding URI to String and network interface support changes

### PR DESCRIPTION
**Pull request by irina-mitrea-luxoft**
This pull request holds the changes from the following pull requests in order to facilitate their merge:
- [Refactor ResourceAddresses in order to support generic Strings instead of URIs](https://github.com/kaazing/gateway/pull/395)
- [Add support for network interface configuration](https://github.com/kaazing/roadmap/issues/663)

The above pull requests will be closed.

### CODE REVIEW

**Comment by irina-mitrea-luxoft** [comment]
@jitsni Hello, Jitu, I have created the PR holding changes for both URI to String refactoring and network interface support. Can you please look over the PR and perform a review in order to establish whether additional changes should be performed prior to merging? Thank you, Irina.

**Comment by irina-mitrea-luxoft** [comment]
@jitsni @sbadugu Investigated whether github could be forced into displaying all the changed files within a PR regardless of size; based on http://stackoverflow.com/questions/9702795/large-github-commit-diff-not-shown a workaround to the issue would be using the link concatenated with the ".patch" token (see [patch link](https://github.com/kaazing/gateway/pull/437)), however this will remove the github specific UI formatting and simply display a basic patch.

**Comment by sbadugu** [comment]
Thanks @irina-mitrea-luxoft ! 
@jitsni What do you prefer ?

**Comment by irina-mitrea-luxoft** [comment]
@jitsni @sbadugu Hello, as soon as we know whether additional changes should be performed on this PR, @NicoletaOita can run a set of itests on these changes. Thank you.

**Comment by jitsni** [comment]
Do you want to resolve conflicts before I look in my IDE ? I think testing can proceed in parallel.

**Comment by irina-mitrea-luxoft** [comment]
@jitsni @sbadugu Hello, Jitu, I have taken the changes from upstream and fixed the conflicts and failing tests. During the merge there where quite a few changes on DefaultClusterContext and WsebConnector which could use some extra review. There are still some failing tests but I think that is only due to my environment since the gateway build does not pass on my Windows machine.

Can you please provide me with an overall code review feedback for this PR in order to know if any changes would be needed? Thank you, Irina.

**Comment by jitsni** [comment]
The build passes for me.
* NetworkInterfaceResolutionIT.java can be there in the top level package itself. 

I think we should merge it and fix any issues in other PRs.

**Comment by irina-mitrea-luxoft** [comment]
@jitsni Hello, Jitu, I have moved NetworkInterfaceResolutionIT two levels up in the package hierarchy as per your suggestion. Thank you, Irina.

**Pull request merged**
