### PR TITLE
Removed redundant itests and added a new spec test.

### PR DESCRIPTION
**Pull request by NicoletaOita**
Removed redundant itests and added a new spec test.

### CODE REVIEW

**Comment by cmebarrow** [comment]
@NicoletaOita Looking good. Please remove the org/kaazing/gateway/transport/wsn/extensions/pingpong/PingPongExtensionIT.java class and associated scripts now everything is covered by the specification tests.

**Comment by cmebarrow** [comment]
@NicoletaOita This looks fine now. But two of the new ping-pong spec tests failed on the Travis build. I am looking into it.

**Comment by cmebarrow** [comment]
@NicoletaOita Hi Nicoleta, the Travis build failed because the version of k3po that is being used does not contain your changes to the pingpong specification scripts. Please update the k3po version in the gateway root pom.xml file to the latest released version as follows, then hopefully the build will go through okay:
```
  <k3po.version>3.0.0-alpha-5</k3po.version>
```

**Comment by NicoletaOita** [comment]
@cmebarrow Hi Chris, I updated the k3po version. Please let me know if the Travis build passes or if there is something else that I should change.

**Comment by cmebarrow** [comment]
Build failed in nio layer, unrelated to these changes. I have restarted the build.

**Comment by cmebarrow** [comment]
@NicoletaOita Travis build is failing because of changes in the k3po tcp specification project, which your PR is up taking because it takes a later k3po version to pick up your spec test changes. I am working on a fix to allow gateway to uptake latest k3po. I already did it for 4.x release (gateway.server).

**Comment by cmebarrow** [comment]
My PR to uptake latest k3po is https://github.com/kaazing/gateway/pull/385. It should get merged soon.

**Comment by cmebarrow** [comment]
@NicoletaOita Let me know if you still have isssues

**Comment by NicoletaOita** [comment]
@cmebarrow I pulled the latest changes from develop into my branch, so you may merge the PR.

**Pull request merged**
