### PR TITLE
Fix for issue #518: Http proxy is adding its own unauthorized content to http response that are unauthorized

### PR DESCRIPTION
**Pull request by msalavastru**
This is a fix for [issue 518](https://github.com/kaazing/tickets/issues/518).

### CODE REVIEW

**Comment by msalavastru** [comment]
@jitsni Looks like this change is causing problems for tests such as [HttpProxyRequestIT#getMethodStatus401](https://github.com/msalavastru/gateway/blob/develop/service/http.proxy/src/test/scripts/org/kaazing/gateway/service/http/proxy/http.proxy.get.method.status.401.rpt) that do not send Content-Length at all, but send chunked content. The test fails because it receives injected content.

It is not clear to me when do we want to inject content. 

- if Content-Length is present do not inject
- if Content-Length is not present, we probably should not inject also, right?

**Comment by jitsni** [comment]
Looks good. I would reorganize something like the following:

```
        HttpStatus httpStatus = httpResponse.getStatus();
        boolean noContent = content == null || (content.length() == 0 && content.isComplete());

        if (contentLength == null && contentAutomaticallyInjectable(httpStatus) && !httpResponse.isContentExcluded() &&
                noContent) {
            IoBufferAllocatorEx<?> allocator = session.getBufferAllocator();
        ...
```

When there is Content-Length header, just don't inject any new content (it doesn't matter whether HttpContent is null or not).

**Comment by msalavastru** [comment]
@jitsni Thanks for your suggestion, I have updated the PR with these changes.

**Comment by jitsni** [comment]
Good work. Pushing it. @dpwspoon you should test with this fix.

**Pull request merged**
