### PR TITLE
Add a connect(ResourceAddress...) variant to ServiceContext.

### PR DESCRIPTION
**Pull request by cmebarrow**

### CODE REVIEW

**Comment by cmebarrow** [comment]
David, when you merge could you re-release gateway? thanks,Chris

**Comment by dpwspoon** [comment]
Release will be 5.0.1.21

**Comment by cmebarrow** [comment]
Thanks, but 5.0.1.21 is already out I think, so 5.0.1.22?

**Comment by dpwspoon** [comment]
Yes, sorry.  I mean 5.0.1.22

**Pull request merged**
