### PR TITLE
Tcp extensions API and implementation

### PR DESCRIPTION
**Pull request by cmebarrow**
Add support for of extensions for the TCP transport. Implementations of TcpExtensionFactorySpi specified in META-INF/services files are loaded using service loader (see TcpExtensionFactory), and invoked during bind to see which TcpExtension objects should be activated for each new IoSession. See design document: [TCP extension framework for CE 5.0](https://docs.google.com/document/d/1DePs8l4LYrFQmo3fAldhd3ahUQ-4lyJaWqbl4csztJM/edit#heading=h.1tdswn4f237p) for more details.

This pull request also includes restructuring of the transport/nio classes to put all private classes in the internal package. The only public classes are TcpExtensionFactorySpi and TcpExtension. Some other modules in gateway currently (and incorrectly) make direct use of NioSocketAcceptor. This is only in tests, except for the proxy service (ServiceConnectManager). This pull request does not attempt to address this. The assumption is that as we restructure other modules we will at that time make changes to ensure they don't import internal classes from transport/nio or anywhere else.

### CODE REVIEW

**Comment by cmebarrow** [comment]
@krismcqueen Please review the extra changes I added, especially those added today (26 jun), including resource injection in TransportFactory

**Comment by krismcqueen** [comment]
@cmebarrow I don't see the call to TransportFactory.injectResources() in GatewayContextResolver.  Am I missing something?  Everything else looks great.

**Comment by cmebarrow** [comment]
@krismcqueen Please go ahead and merge this pull request since I now have the bandwidth extension working in enterprise.gateway

**Comment by krismcqueen** [comment]
@cmebarrow sounds good, I'll just check in with you tomorrow about the GatewayContextResolver question I had asked to make sure my understanding is correct.

**Comment by cmebarrow** [comment]
@krismcqueen I haven't changed GatewayContextResolver to use TransportFactory.injectResources() yet since I wanted to progress on the EE work. I will see if I can do that tomorrow am before you merge.

**Comment by cmebarrow** [comment]
@krismcqueen Changes to GatewayContextResolver are now in. Please merge if you think all is OK.

**Comment by krismcqueen** [comment]
@cmebarrow looks great!

**Pull request merged**
