### PR TITLE
add ws extensions functionality in WsnConnector

### PR DESCRIPTION
**Pull request by danibusu**
This pull request can only be merged after [this](https://github.com/k3po/k3po/pull/349) one.

### CODE REVIEW

**Comment by dpwspoon** [comment]
Looks like test failure is related to this:   OpeningHandshakeIT.shouldFailConnectionWhenResponseHeaderSecWebSocketExtensionsNotNegotiated Specified behavior did not match expected:<...Socket-Extensions" "[primary, secondary"

**Comment by danibusu** [comment]
@dpwspoon I wrote in the initial comment that [this PR](https://github.com/k3po/k3po/pull/349) on the k3po repo should be merged first. After it is merged and a new k3po relese is out, I can update the k3po and the tests will pass. Thanks!

**Comment by dpwspoon** [comment]
Thanks.  Merged k3po PR, k3po release 3.0.0-alpha-45 is scheduled to run, http://jenkins.kaazing.wan/view/release_build/job/k3po-release/.  Please ping me when K3po version is updated in this PR

**Comment by danibusu** [comment]
@dpwspoon I updated the k3po dependency so it can be reviewed. Thanks!

**Pull request merged**
